services:
  postgres:
    image: postgres:17.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    container_name: 'postgresql-container'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # начальная схема БД
    ports:
      - 5432:5432